---
ID: "0dcbcca4-e78c-48d5-84f5-d9889a2d8a7d"
Parent: "5debc58d-a20f-461b-a57f-39d4bc50e755"
Template: "63d04756-2704-482d-8562-17b818dcdc6c"
Path: /sitecore/system/Modules/Flex/Configuration/Configs/Phone Validator Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190116T135445Z
    - ID: "d9e2611d-71da-43e7-9e49-1d128f922ec2"
      Hint: Regular Expression
      Value: "^[0|\+]{1}[0-9|\ ]{6,}$"
