---
ID: "b9c911c0-75ff-49f5-bd8c-513d91566a13"
Parent: "c9f22ea8-a04f-4466-be48-35635eb9e8a9"
Template: "c9f22ea8-a04f-4466-be48-35635eb9e8a9"
Path: /sitecore/templates/Flex/Components/Visibility Dependency/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141108T165623
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
