---
ID: "86385f7f-1f1c-4037-8313-cee3a1a9b046"
Parent: "5cbcde45-f0a9-4f6d-8273-685249abddf6"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Flex/Fields/Input Fields/DatePicker Field/Form Configuration
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141105T094330
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
