---
ID: "69b9dc57-f926-4c6a-96b0-25c076aabbe1"
Parent: "569c95e7-c1e0-4dd7-ae84-9673dbd3cb18"
Template: "569c95e7-c1e0-4dd7-ae84-9673dbd3cb18"
Path: /sitecore/templates/Flex/Components/Navigation Pane/__Standard Values
DB: master
SharedFields:
- ID: "08c0835e-5179-4b68-b759-29b795aa9b89"
  Hint: Show Navigation Pane
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140623T105148
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
