---
ID: "8cb12e1e-30fe-4a3c-8276-5f0bc8c43d7a"
Parent: "cf1ca8d4-a6d0-43d0-afb2-ad7d72ab9997"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Configuration/Configuration/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130417T105814
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\tobias.studer
