---
ID: "1484de3f-bfc7-4e1b-88f1-21a712bef74a"
Parent: "773ff85e-c512-4825-a4ea-1ffb181525c9"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Flex/Sections/Reusable Section/Form Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140428T133451
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
