---
ID: "14291e98-30be-486c-bed7-0815d77194c3"
Parent: "54c4ece0-ab7f-4dc3-b18c-facd92bc1a1d"
Template: "54c4ece0-ab7f-4dc3-b18c-facd92bc1a1d"
Path: /sitecore/templates/Flex/Global/Specifications Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {54C4ECE0-AB7F-4DC3-B18C-FACD92BC1A1D}
    {47D4110F-7D21-4DC8-89F0-41302DB57637}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140619T151900
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
