---
ID: "f19a7a85-5ed1-45b1-aed9-b27e69d17d7d"
Parent: "dadb4f93-477f-491f-a905-c4005c452e67"
Template: "1a9b6300-4652-477c-a4b5-b2a64e86b29f"
Path: /sitecore/system/Settings/Rules/Definitions/Tags/Unic Configuration Module
DB: master
BranchID: "60e3e35b-cef9-4afa-9f89-204ed015ccb9"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141002T142246
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
