---
ID: "128a1a19-7984-491d-b9b5-13d110bcc9d6"
Parent: "4906df7c-b200-4825-b1ac-488d7d928452"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Flex/Plugs/Load Plugs/QueryString Loader/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180313T112636Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
