---
ID: "83f47219-b797-4ac4-8437-910fa015cde5"
Parent: "a0bed174-2c0f-49c2-9d8a-fc0a124a3129"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Flex/Fields/List Fields/List Field/Form Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140925T130529
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
